# Generated by Django 2.1.4 on 2018-12-28 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0002_customuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='registration_number',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Invalid Registration Number', regex='[0-9]{8}')]),
        ),
    ]
