# Generated by Django 2.1.4 on 2019-01-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0009_customuser_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='noti_messages',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
