# Generated by Django 2.1.4 on 2018-12-29 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comportal', '0002_auto_20181229_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='complain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='comportal.Complain'),
        ),
    ]
