# Generated by Django 2.1.4 on 2019-01-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comportal', '0005_complain_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='type',
            field=models.CharField(choices=[('I', 'individual'), ('G', 'general')], default='G', max_length=1),
        ),
    ]
