# Generated by Django 2.1.4 on 2019-01-10 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comportal', '0006_auto_20190110_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
